variable "aws_region" {}
variable "vpc_cidr" {}
variable "vpc_name" {}
variable "key_name" {}
variable "azs" {}
variable "environment" {}
variable "instance_type" {}
variable "public_cidrs" {}
variable "private_cidrs" {}
variable "ami" {}
