---
- name: Deploy Nginx To Webservers
  hosts: webservers
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
  - name: Perform Apt Update
    shell: apt update
  - name: Install Nginx
    shell: apt install -y nginx
  - name: Start Nginx Service
    shell: service nginx start
  tags:
  - web

- name: Deploy Nginx To App & DB Servers
  hosts: webservers:appservers:dbservers
  gather_facts: yes
  become: yes
  become_user: root
  vars:
    hostname: "{{ ansible_facts['hostname']}}"
  tasks:
  - name: Perform Apt Update
    shell: apt update
  - name: Install Nginx
    shell: apt install -y nginx
  - name: Start Nginx Service
    shell: service nginx start
  - name: Write Some Thing To Indexfile
    shell: echo "<h1>{{hostname}}</h1>" >> /var/www/html/index.nginx-debian.html
  tags:
  - all

